name: Build Eclipse eMoflon
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'feature/<stuff>'
    branches:
      - main
      - 'feature/**'
    # Run pipeline for release tags
    tags:
      - 'v*.*.*'

env:
  ECLIPSE_ARCHIVE: eclipse-emoflon-linux-user-ci
  TEST_PROJECT: org.emoflon.ci.helloworld.tests
  JAR_NAME: helloworld-testrunner

jobs:
  # hello world CI example
  build:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build."
      - name: Install correct Java version
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Get Eclipse archive
        run: curl -s https://api.github.com/repos/maxkratz/emoflon-eclipse-build/releases/latest \
          | grep "$ECLIPSE_ARCHIVE.*zip" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -qi -

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: org.emoflon.ci.helloworld.tests/build/reports/*.xml
